### ISSUE TITLE
Issues with March 7 update

### ISSUE THREAD

**Issue by JellyGlyde** [batram/UCH-EvenMorePlayers#11]
The recent update to UCH seems to have introduced some issues with the mod. We played with 5 players on 3/6 and had 0 issues, but after we all updated and played with 6 on 3/8, objects were showing inconsistently to different players, or not at all. Games would not end when the score limit was reached, instead just zooming on the winner until the host backs out.

This mod is fantastic, thank you for the joy you have brought me and my friends

**Comment by batram** [comment]
Thanks for reporting the issue.

Looking at [the official UCH discord](https://discord.gg/UCH) many other players are also reporting similar issues after the update.
At the moment it looks to me like the update in general might be a bit buggy.

Did you specifically try with and without the mod active?

**Comment by JellyGlyde** [comment]
Oh interesting. No, we only tried with the mod. I can try again without later today.

**Comment by batram** [comment]
According to the devs of the game the overloaded servers should now be back to normal.
And the errors and sync issues should be gone.

If you notice the issues are still present and mod specific, please let me know.
