### ISSUE TITLE
Text Overflow Issues on Pandamonium Update

### ISSUE THREAD

**Issue by Avakining** [batram/UCH-EvenMorePlayers#16]
As shown in the screenshot, the "play online" text overflows the boxes on the new update. Otherwise, seems to work just fine!

<img width="667" alt="Screenshot 2024-05-13 at 18 42 28" src="https://github.com/batram/UCH-EvenMorePlayers/assets/25210618/14ff104b-b9e3-4a09-a484-b40b9a5122fa">

**Comment by batram** [comment]
Thanks for the report.
You shocked me a bit with `Overflow Issues`, as my brain skipped right past the `Text` part.

Seems to only happened after being a while in the menu and sporadically for me.
Is it constant for you or do you have a way to reliably reproduce the bug?

**Comment by Avakining** [comment]
It's happened every time I've opened the main menu (which has only been a handful of times today).

Don't know if matters, but I'm running the macOS version of UCH.

**Comment by batram** [comment]
Just saw it happen once on Windows and now am struggling to reproduce the issues.

The code for button placement has always been a bit wonky, I will try to get this fixed.

**Comment by batram** [comment]
> Don't know if matters, but I'm running the macOS version of UCH.

@Avakining could you please verify if this new release resolves the issue on macOS:
https://github.com/batram/UCH-EvenMorePlayers/releases/tag/0.9.0.2.2

**Comment by Avakining** [comment]
Seems to work!

The zip did fail to extract using the built-in Archive Utility, though, because it said the checksum was wrong.

**Comment by batram** [comment]
Thanks for checking

Will repack the archive
