### ISSUE TITLE
Possible with online play?

### ISSUE THREAD

**Issue by Kenpari** [batram/UCH-EvenMorePlayers#2]
Just wanted to see if it was possible to utilize this mod to play with more than 4 players online. I understand the answer is probably no, but I didn't see any info, so I wanted to make sure before I cast aside the idea.

**Comment by batram** [comment]
Yes, you can use this mod to play online with more than 4 players.

From the latest release info:
```
P2P: 100? players (maybe)
Unity Matchmaking: 8 players (limited by server side Unity Relay?)
```

All players need the mod.
The mod is disabled in normal Online play and only enabled when playing online via the "More" button.

![1](https://user-images.githubusercontent.com/1382274/175807071-2c539967-54fc-4857-938e-7a339503e0e5.png)

Will update the README to include this info.
