### ISSUE TITLE
Skins don't work for additional players

### ISSUE THREAD

**Issue by Kenpari** [batram/UCH-EvenMorePlayers#3]
Figured you might already know this, but thought I'd field it in the off-chance you don't and it's possible to implement.

It seems like skins don't work for any players beyond the first four players to join the lobby. The skin they select appears in the Treehouse and during Prop Selection, but not during actual play in the level. Also noticed that additions beyond the fourth player don't appear on the score modifiers board in the Treehouse, unsure if hitting the buttons with them actually does anything.

**Comment by batram** [comment]
Thanks for your reports.
At the moment I am having problems recreating the skin issue.
I assume you mean the outfits of the players and the different animals (Squirrel, Black/Red Skunk, ...) you can select.
I tried it with more than 4 local and network players and can not reproduce missing skins.

![image](https://user-images.githubusercontent.com/1382274/177340260-abea139f-51cb-4aa9-b63b-bc21782dca0b.png)

Anyway to reliable reproduce the issue? 
Is it with local or network or both types of players?
What game mode?

The score modifiers work for the players that are not displayed on the board in the treehouse.

![image](https://user-images.githubusercontent.com/1382274/177341721-b3ce1fa6-6ee3-46bf-be4a-6b81908cfba7.png)

For now I personally don't have any plans to work on updating the score modifiers board in the Treehouse.
But I will create a separate issue and am open to pull requests. 
Something like only showing modified players on the board or keeping the last changes on top, might be a way to use the limited space available.

**Comment by Kenpari** [comment]
I will try to reproduce the skin issue again when we next play with more players. The player in question had just unlocked the skin during our play session, so that may be related? In any case, I’ll post an update when I’m able to confirm whether I can reproduce it or not. 

Also, this was during online play via the More tab. It could have been a one and done sort of thing, as I’ve encountered other certain bugs in vanilla during online play, such as games not loading or players joining in two player slots at one time and only being able to select characters with the second slot, so it could be an obscure vanilla bug I just hadn’t seen yet.
