### ISSUE TITLE
Controller Input Issues

### ISSUE THREAD

**Issue by Kenpari** [batram/UCH-EvenMorePlayers#4]
It looks like this mod somehow breaks controller inputs in an odd way, but it is circumventable. The issue also disappears when removing the mod.

When launching the game through steam with a Playstation 5 controller in big picture mode, Ultimate Chicken Horse fails to recognize the input (doesn't work for anything) when launched. This only happens if you don't have "Playstation controller support" ticked in Big Picture Mode's controller settings.

This also happens with the Xbox 360 controller, if you don't have "Xbox controller support" ticked in big picture mode's setting.

The vanilla game recognizes these inputs fine even if you don't have the controller option ticked in Steam's big picture mode settings.  Not sure about Switch Pro controllers, as one of our players was using one, but we didn't check her Steam controller settings.

**Comment by batram** [comment]
Thanks for figuring out the issues and possible solutions. 

The mod needs to change the mode of the library used to get more than 4 controllers to work locally. 
(`InputManager.EnableNativeInput` is forced to always be `true`.) 
That is the most likely explanation for the changes you encountered.

I don't think I can fix the issues directly and the best solution is to document the need to use `Xbox controller support` and `Playstation controller support` in `Big Picture Mode` at some place (maybe Readme or a Wiki entry). 
I will try to find a few more people to verify the settings. 

An alternative would be to make a config file option to disable the `EnableNativeInput` mod, but that would limit local players to 5 (4 controllers + 1 keyboard).

**Comment by batram** [comment]
Created a wiki page to help with controller issues:
https://github.com/batram/UCH-EvenMorePlayers/wiki/Controller-Input-Issues
