### ISSUE TITLE
Lobby continuously says that it's full, even though there's only 5 of us. 

### ISSUE THREAD

**Issue by ClaveBBY** [batram/UCH-EvenMorePlayers#7]
My friends and I get 4 into the lobby, but before our 5th can join it says that the lobby is full. 
![unknown](https://user-images.githubusercontent.com/115127901/194202368-d55d7eee-6666-43ba-a17d-2e260ba11063.png)

**Comment by batram** [comment]
Thank you for the report and screenshot.

Until now I only tested the new version with one steam account and multiple instances of the game and was able to get more than 4 players in a lobby, but this might not work for different steam accounts. 

With the old online services there was a hard limit (of 8 players) on the server side, not sure about the new online service.

Would be awesome if you could provide the contents of your `output_log.txt` file when the issue occurs.

I will look into the issue.

**Comment by batram** [comment]
Thank you again @ClaveBBY for the report.

I was able to reproduce the issue and it should be fixed with release [0.9.0.1](https://github.com/batram/UCH-EvenMorePlayers/releases/tag/0.9.0.1).
